development:
  host: localhost
  adapter: mysql2
  database: recipe_app_development
  pool: 5
  username:
  password:

test:
  host: localhost
  adapter: mysql2
  database: recipe_app_test
  pool: 5
  username:
  password:

production:
  adapter: mysql2
  database: recipe_app_production
  pool: 5
  username: recipe_app
  password: <%= ENV['RECIPE_APP_DATABASE_PASSWORD'] %>
